#+ summary: Example query to construct a new simplified graph with ship information
#+ endpoint: https://globalise-data.diginfra.net/repositories/GLOBALISE-DATA?infer=false
#+ method: GET
#+ tags:
#+   - ships

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
    ?ship a sem:Object ;
          rdfs:label ?ship_label .
} WHERE {
    
    ?ship a sem:Object ;
         sem:actorType <https://data.globalise.huygens.knaw.nl/id/vocabulary/actortype/ship> ;
         rdfs:label ?label .
    
    # No reasoning until we have modelled the preferredURI
    ?uri owl:sameAs|^owl:sameAs ?ship .  # must be present in our linkset
    
    BIND(CONCAT(?label, ' (ship)') AS ?ship_label)
    
}
