#+ summary: Example query to fetch classifications from our thesauri
#+ endpoint: https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/globalise
#+ method: GET
#+ tags:
#+   - classifications

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT * WHERE {
    
    ?concept a skos:Concept ;
  		rdfs:label ?label .  # superProperty of skos:prefLabel?
    
    # Very basic searching
    FILTER(REGEX(?label, ?_search, 'i'))
    
}
